### ISSUE TITLE
Omit new events for plugin extension for tabline.wez

### ISSUE THREAD

**Issue by michaelbrusegard** [MLFlexer/resurrect.wezterm#58] opened 2024-08-28 10:32 UTC
I recently developed a tab bar plugin: https://github.com/michaelbrusegard/tabline.wez and I want to have an extension for resurrect. I specifically need the events for when the fuzzy finder is opened and when it is closed. If you have any good ideas for how the tabline should look with the extension that would be cool. Also if you have some feedback in how I can make the plugin better I am very open for that

**Comment by michaelbrusegard** [comment] 2024-08-28 18:33
I think so, the events are for enabling and disabling a custom tab bar specific to the plugin. As long as I have that it will work

**Comment by joncrangle** [comment] 2024-08-28 19:07
I just submitted a PR that adds "start" and "finished" emitters that also return `window` and `pane`. 

This should hopefully resolve this issue

https://github.com/MLFlexer/resurrect.wezterm/pull/59

**Comment by joncrangle** [comment] 2024-08-29 12:13
@michaelbrusegard your plugin has a cool look and feel out of the box, and config should be familiar for people who use nvim.

@MLFlexer I don't know your thoughts, but I think it might be cool if a tab section showed the `md_sleep_off` icon along with the window title if the resurrect fuzzy picker is open.

**Comment by michaelbrusegard** [comment] 2024-08-29 12:21
> your plugin has a cool look and feel out of the box

I am so glad you think so! I hope it can be useful for many people. The extension can customize the tab bar completely or just slightly (it is very versatile). It can also show a small loading indicator for the loading event. I can probably create something myself but I think it is better if you help decide how the extension should work and which events it should use. Though personally, I would like at least a custom look when you are inside the picker (for both the workspace switcher and for resurrect :)

**Comment by MLFlexer** [comment] 2024-08-30 07:54
Sorry for my slow response. Uni has started again, so I don't have as much free time as I had over the summer break 😃 

@michaelbrusegard I have merged  #59  adding the emitters 


> @MLFlexer I don't know your thoughts, but I think it might be cool if a tab section showed the `md_sleep_off` icon along with the window title if the resurrect fuzzy picker is open.

I havn't had time to try out the plugin, so I don't really have any strong oppinions about this. But it sounds fine 😄

**Closed** 2024-08-30 07:54 UTC

**Comment by michaelbrusegard** [comment] 2024-08-30 11:59
The `resurrect.fuzzy_load.finished` event is not working, but the events for https://github.com/MLFlexer/smart_workspace_switcher.wezterm/issues/34 is working correctly. I was also wondering if there are any other information that would be useful to have in the tab-extension for this plugin. Right now I am showing a Selection text when using the fuzzy picker. I also added a loading indicator that shows up on periodic save (I have not seen it yet so that event may also have issues, but It can also be that I have never looked at the tab-bar when a periodic save has happened).

I do not really need the window and pane to be returned for these events since I am not using them though it does not harm. Also it would be nice if there was separate events for resurrecting window or workspace when opening the fuzzyloader so I can show different text for each. I dont need separate close events

**Comment by joncrangle** [comment] 2024-08-30 15:15
> The `resurrect.fuzzy_load.finished` event is not working, but the events for [MLFlexer/smart_workspace_switcher.wezterm#34](https://github.com/MLFlexer/smart_workspace_switcher.wezterm/issues/34) is working correctly. I was also wondering if there are any other information that would be useful to have in the tab-extension for this plugin. Right now I am showing a Selection text when using the fuzzy picker. I also added a loading indicator that shows up on periodic save (I have not seen it yet so that event may also have issues, but It can also be that I have never looked at the tab-bar when a periodic save has happened).
> 
> I do not really need the window and pane to be returned for these events since I am not using them though it does not harm. Also it would be nice if there was separate events for resurrecting window or workspace when opening the fuzzyloader so I can show different text for each. I dont need separate close events

Were you able to get it working? 
I was able to use the events in my local config (tested on Mac and Windows) with:
```lua
   local event_listeners = {
    { event = 'resurrect.fuzzy_load',                        text = wezterm.nerdfonts.md_sleep_off .. ' Resurrect ' },
    { event = 'smart_workspace_switcher.workspace_switcher', text = wezterm.nerdfonts.cod_terminal_tmux .. ' Smart Workspace Switcher ' },
  }

  for _, v in ipairs(event_listeners) do
    wezterm.on(v.event .. '.start', function(window, _)
      local colors = wezterm.get_builtin_color_schemes()['Catppuccin Mocha']

      window:set_right_status(wezterm.format({
        { Foreground = { Color = colors.ansi[6] } },
        { Text = v.text },
      }))
    end)
    wezterm.on(v.event .. '.finished', function(window, _)
      window:set_right_status(wezterm.format({
        { Text = '' },
      }))
    end)
  end
```

**Comment by michaelbrusegard** [comment] 2024-08-30 16:38
@joncrangle I am so stupid... I wrote `stop` instead of `finished`
The tabline.wez extension for resurrect now works perfectly. Are you able to test if the `cpu` and `ram` components works on windows or linux if you are using the tabline plugin

**Comment by joncrangle** [comment] 2024-08-30 23:56
> @joncrangle I am so stupid... I wrote `stop` instead of `finished` The tabline.wez extension for resurrect now works as expected. Are you able to test if the `cpu` and `ram` components works on windows or linux if you are using the tabline plugin

No worries! I can confirm that the cpu and ram components work on Arch linux. They did not work on Windows: error output from debug window:
```
19:46:07.782 ERROR wezterm_gui::termwindow > while processing update-status event: runtime error: ...ZstablinesDswez\plugin\tabline\components\window\cpu.lua:58: bad argument #2 to 'format' (number expected, got string)
stack traceback:
        [C]: in function 'string.format'
        ...ZstablinesDswez\plugin\tabline\components\window\cpu.lua:58: in function 'tabline.components.window.cpu.update'
        ...michaelbrusegardsZstablinesDswez\plugin\tabline\util.lua:86: in function 'tabline.util.extract_components'
        ...elbrusegardsZstablinesDswez\plugin\tabline\component.lua:74: in upvalue 'create_sections'
        ...elbrusegardsZstablinesDswez\plugin\tabline\component.lua:135: in function 'tabline.component.set_status'
        ...DscomsZsmichaelbrusegardsZstablinesDswez/plugin/init.lua:38: in function <...DscomsZsmichaelbrusegardsZstablinesDswez/plugin/init.lua:37>
```

A couple other things I found:
1) I tried using the resurrect extension, but there's a spelling error on the filename so it doesn't import properly. If you rename ressurect.lua to `resurrect.lua` it will fix it.

2) If the process isn't found, it might be worth querying the `domain` instead of defaulting to `ssh`. There are all kinds of possible domains that a tab might be (SSHMUX, DOCKER, etc.). I noticed this because when you bring up the Wezterm debug menu, it's tab process title defaulted to ssh so I found it a bit strange.

Feature request(s) (I can create an issue or discussion in your repo if you prefer):

1) Are you interested in adding an option involving process icons within the tab bar? That's what I use in my config at the moment, and I like it because it lets me have a very minimal tab bar. I modified it from folke's dotfiles, so I think the attribution is important within the code block below. I wasn't sure how you wanted to deal with this option, so at the moment it's structured as a different file, but you might prefer providing it as opts to `process.lua` if it's a feature you're interested in incorporating.

```lua
local wezterm = require('wezterm')

local foreground_process_name = ''

local icons = {
  ['C:\\WINDOWS\\system32\\cmd.exe'] = wezterm.nerdfonts.md_console_line,
  ['Topgrade'] = wezterm.nerdfonts.md_rocket_launch,
  ['bash'] = wezterm.nerdfonts.cod_terminal_bash,
  ['btm'] = wezterm.nerdfonts.mdi_chart_donut_variant,
  ['btop'] = wezterm.nerdfonts.md_chart_areaspline,
  ['btop4win++'] = wezterm.nerdfonts.md_chart_areaspline,
  ['cargo'] = wezterm.nerdfonts.dev_rust,
  ['curl'] = wezterm.nerdfonts.mdi_flattr,
  ['docker'] = wezterm.nerdfonts.linux_docker,
  ['docker-compose'] = wezterm.nerdfonts.linux_docker,
  ['fish'] = wezterm.nerdfonts.md_fish,
  ['gh'] = wezterm.nerdfonts.dev_github_badge,
  ['git'] = wezterm.nerdfonts.dev_git,
  ['go'] = wezterm.nerdfonts.seti_go,
  ['htop'] = wezterm.nerdfonts.md_chart_areaspline,
  ['kubectl'] = wezterm.nerdfonts.linux_docker,
  ['kuberlr'] = wezterm.nerdfonts.linux_docker,
  ['lazydocker'] = wezterm.nerdfonts.linux_docker,
  ['lazygit'] = wezterm.nerdfonts.cod_github,
  ['lua'] = wezterm.nerdfonts.seti_lua,
  ['make'] = wezterm.nerdfonts.seti_makefile,
  ['node'] = wezterm.nerdfonts.mdi_hexagon,
  ['nvim'] = wezterm.nerdfonts.custom_neovim,
  ['pacman'] = wezterm.nerdfonts.md_pac_man,
  ['paru'] = wezterm.nerdfonts.md_pac_man,
  ['powershell.exe'] = wezterm.nerdfonts.md_console,
  ['psql'] = wezterm.nerdfonts.dev_postgresql,
  ['pwsh.exe'] = wezterm.nerdfonts.md_console,
  ['ruby'] = wezterm.nerdfonts.cod_ruby,
  ['sudo'] = wezterm.nerdfonts.fa_hashtag,
  ['vim'] = wezterm.nerdfonts.dev_vim,
  ['wget'] = wezterm.nerdfonts.mdi_arrow_down_box,
  ['zsh'] = wezterm.nerdfonts.dev_terminal,
}

return {
  update = function(tab)
    -- Inspiration: @folke https://github.com/folke/dot/blob/master/config/wezterm/tabs.lua
    if tab.active_pane and tab.active_pane.foreground_process_name then
      foreground_process_name = tab.active_pane.foreground_process_name
      foreground_process_name = foreground_process_name:match('([^/]+)/?$') or
          foreground_process_name
    end
    local foreground_process_icon = icons[foreground_process_name] or ''
    return foreground_process_name ~= '' and foreground_process_icon or wezterm.nerdfonts.dev_terminal
  end,
}
```

2) Also modified from folke, an indicator if a pane is zoomed, which I also incorporated into my current tab bar. You can check out mine at https://github.com/joncrangle/wezterm/blob/master/tabs.lua where I also implemented the zoom indication feature.

**Comment by michaelbrusegard** [comment] 2024-09-03 12:13
Those are som great ideas. Maybe discuss it in the tabline repo instead, because I didnt see the message until now haha.
